[project]
name = "llm_hygiene"
version = "0.0.1"
description = "A payload compression toolkit that makes it easy to create ideal data structures for LLMs; from training data to chain payloads."
readme = "dynamic"